= 2. OVERVIEW
:toc: macro

link:01-introduction.adoc[< Previous: 1. INTRODUCTION] | link:03-specification.adoc[Next: 3. SPECIFICATION >]

== 2.1 Relation to Other Protocols

The following diagram illustrates the place of the internet protocol in the protocol hierarchy:

....
                 +------+ +-----+ +-----+     +-----+
                 |Telnet| | FTP | | TFTP| ... | ... |
                 +------+ +-----+ +-----+     +-----+
                       |   |         |           |
                      +-----+     +-----+     +-----+
                      | TCP |     | UDP | ... | ... |
                      +-----+     +-----+     +-----+
                         |           |           |
                      +---------------------------+
                      |    Internet Protocol      |
                      +---------------------------+
                                 |
                    +---------------------------+
                    |   Local Network Protocol  |
                    +---------------------------+
....

Internet Protocol interfaces on one side to the higher level host-to-host protocols and on the other side to the local network protocol.

== 2.2 Model of Operation

The model of operation for transmitting a datagram from one application program to another is illustrated by the following scenario:

We suppose that this transmission will involve one intermediate gateway.

1.  The sending application program prepares its data and calls on its local internet module to send that data as a datagram and passes the destination address and other parameters as arguments of the call.

2.  The internet module prepares a datagram header and attaches the data to it. The internet module determines a local network address for this internet address. In this case it is the address of a gateway.

3.  The internet module sends this datagram and the local network address to the local network interface.

4.  The local network interface creates a local network header, and attaches the datagram to it, then sends this result via the local network.

5.  The datagram arrives at a gateway host wrapped in the local network header, the local network interface strips off this header, and turns the datagram over to the internet module. The internet module determines from the internet address that the datagram is to be forwarded to another host in a second network. The internet module determines a local net address for the destination host. It calls on the local network interface for that network to send the datagram.

6.  This local network interface creates a local network header and attaches the datagram sending the result to the destination host.

7.  At the destination host the datagram is stripped of the local net header (and handled by the local network interface) and handed to the internet module.

8.  The internet module determines that the datagram is for an application program in this host. It passes the data to the application program in response to a system call, passing the source address and other parameters as results of the call.

[TIP]
.Scenario: The Connecting Flight
====
Think of a packet traveling from your laptop to a server as a passenger taking a connecting flight.
* **Your Laptop (Host A)** is the departure airport. You (the Application) get on the plane (the Datagram).
* The plane flies to a **Hub Airport (Gateway/Router)**.
* You get off the first plane. The airport staff (Internet Module) checks your ticket (Header) and sees you need to go to a different destination.
* You board a new plane (Local Network transmission) on a different airline to get to the final destination.
* The protocols are the rules that ensure you and your luggage (Data) get transferred correctly between planes.
====

== 2.3 Function Description

The function or purpose of Internet Protocol is to move datagrams through an interconnected set of networks. This is done by passing the datagrams from one internet module to another until the destination is reached. The internet modules reside in hosts and gateways in the internet system. The datagrams are routed from one internet module to another through networks based on the interpretation of an internet address.

[NOTE]
.Addressing & Fragmentation
====
The two primary mechanisms are:
1.  **Addressing**: Like a postal code, ensuring the packet heads in the right direction.
2.  **Fragmentation**: If a packet is too big for a specific network (like trying to mail a sofa), IP breaks it down into smaller packages (fragments) and reassembles them at the destination.
====

== 2.4 Gateways

Gateways implement internet protocol to forward datagrams between networks. Gateways also implement the Gateway to Gateway Protocol (GGP) to coordinate routing and other internet control information.

In a gateway the higher level protocols need not be implemented and the GGP functions are added to the IP module.

---
link:01-introduction.adoc[< Previous: 1. INTRODUCTION] | link:03-specification.adoc[Next: 3. SPECIFICATION >]

