= GLOSSARY
:toc: macro

link:appendix-b.adoc[< Previous: APPENDIX B] | link:references.adoc[Next: REFERENCES >]

1822::
BBN Report 1822, "The Specification of the Interconnection of a Host and an IMP". The specification of interface between a host and the ARPANET.

ARPANET leader::
The control information on an ARPANET message at the host-IMP interface.

ARPANET message::
The unit of transmission between a host and an IMP in the ARPANET. The maximum size is about 1012 octets (8096 bits).

ARPANET packet::
A unit of transmission used internally in the ARPANET between IMPs. The maximum size is about 126 octets (1008 bits).

Destination::
The destination address, an internet header field.

DF::
The Don't Fragment bit carried in the flags field.

Flags::
An internet header field carrying various control flags.

Fragment Offset::
This internet header field indicates where in the internet datagram a fragment belongs.

GGP::
Gateway to Gateway Protocol, the protocol used primarily between gateways to control routing and other gateway functions.

header::
Control information at the beginning of a message, segment, datagram, packet or block of data.

ICMP::
Internet Control Message Protocol, implemented in the internet module, the ICMP is used from gateways to hosts and between hosts to report errors and make routing suggestions.

Identification::
An internet header field carrying the identifying value assigned by the sender to aid in assembling the fragments of a datagram.

IHL::
The internet header field Internet Header Length is the length of the internet header measured in 32 bit words.

IMP::
The Interface Message Processor, the packet switch of the ARPANET.

Internet Address::
A four octet (32 bit) source or destination address consisting of a Network field and a Local Address field.

internet datagram::
The unit of data exchanged between a pair of internet modules (includes the internet header).

internet fragment::
A portion of the data of an internet datagram with an internet header.

Local Address::
The address of a host within a network. The actual mapping of an internet local address on to the host addresses in a network is quite general, allowing for many to one mappings.

MF::
The More-Fragments Flag carried in the internet header flags field.

module::
An implementation, usually in software, of a protocol or other procedure.

more-fragments flag::
A flag indicating whether or not this internet datagram contains the end of an internet datagram, carried in the internet header Flags field.

NFB::
The Number of Fragment Blocks in the data portion of an internet fragment. That is, the length of a portion of data measured in 8-octet units.

octet::
An eight bit byte.

Options::
The internet header Options field may contain several options, and each option may be several octets in length.

Padding::
The internet header Padding field is used to ensure that the data begins on 32 bit word boundary. The padding is zero.

Protocol::
In this document, the next higher level protocol identifier, an internet header field.

Rest::
The local address portion of an Internet Address.

Source::
The source address, an internet header field.

TCP::
Transmission Control Protocol: A host-to-host protocol for reliable communication in internet environments.

TCP Segment::
The unit of data exchanged between TCP modules (including the TCP header).

TFTP::
Trivial File Transfer Protocol: A simple file transfer protocol built on UDP.

Time to Live::
An internet header field which indicates the upper bound on how long this internet datagram may exist.

TOS::
Type of Service

Total Length::
The internet header field Total Length is the length of the datagram in octets including internet header and data.

TTL::
Time to Live

Type of Service::
An internet header field which indicates the type (or quality) of service for this internet datagram.

UDP::
User Datagram Protocol: A user level protocol for transaction oriented applications.

User::
The user of the internet protocol. This may be a higher level protocol module, an application program, or a gateway program.

Version::
The Version field indicates the format of the internet header.

---
link:appendix-b.adoc[< Previous: APPENDIX B] | link:references.adoc[Next: REFERENCES >]

